### ISSUE TITLE
Modify SpiceDB Schema management to configure more flexible permission and roles

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#169]
Currently, our schema only lets us configure backend and resource, like odin_dagger, but not entities like org, project & team

example we cannot change this schema from any dynamic config file, but from code 
```
definition organization {
	relation organization_admin: user | team#team_member
	permission manage_organization = organization_admin
	permission create_project = organization_admin
	permission create_team = organization_admin
}

definition project {
	relation organization: organization
	relation project_admin: user | team#team_member
	permission manage_project = organization->organization_admin + project_admin
}

definition team {
	relation organization: organization
	relation project: project
	relation team_admin: user
	relation team_member: user
	permission all_actions_team = project->project_admin + organization->organization_admin
	permission manage_team = organization->organization_admin + team_admin
	permission view_team = team_member + team_admin
}

definition user {}
```

if say we need to add a new relation in org, we need to make changes in code. 

we are seeing that for upcoming changes being planned under new schema changes , we would need to make certain changes in entity definitions as well.

Thus, moving to a more flexible configuration yaml
```yaml
organization:
    type: entity
    roles: 
        - name: experimenter
          type: 
            - user
            - team#member
    capabilities:
        - name: litmus_experiment_view
          roles:
            - owner
            - editor

odin:
    type: backend
    resources:
        - name: firehose
            roles: 
            - name: owner
            type: 
                - user
                - root#super_admin
```

**Comment by krtkvrm** [comment]
modifying the yaml to 
```yaml
name: entropy
type: resource_group
namespaces:
  - name: firehose
    roles:
      - name: viewer
        principals:
          - user
          - team_members
      - name: sink_editor
        principals:
          - user
          - team
    permissions:
      - name: view
        roles:
          - firehose/owner
          - organization/owner
          - firehose/viewer
      - name: sink_edit
        roles:
          - firehose/owner
          - firehose/sink_editor
          - org/sink_editor

name: organization
type: system
roles:
  - name: sink_editor
    principals:
      - user
      - team/member
```

**Comment by krtkvrm** [comment]
new format
```yaml
entropy:
  type: resource_group
  namespaces:
    - name: firehose
      roles:
        - name: viewer
          principals:
            - user
            - team
        - name: sink_editor
          principals:
            - user
            - team
      permissions:
        - name: view
          roles:
            - this/owner
            - organization/owner
            - this/viewer
        - name: sink_edit
          roles:
            - this/owner
            - this/sink_editor
            - org/sink_editor

organization:
  type: system
  roles:
    - name: sink_editor
      principals:
        - user
        - team
```
