### ISSUE TITLE
Introduce constant type of attributes in rules config for collecting resource_type in authz

### ISSUE THREAD

**Issue by krtkvrm** [odpf/shield#76]
- Introduce `constant` type of attributes in rules yml, which will use `value` as constant value
```
        - name: create_provider_admin
              path: "/api/v1beta1/provider"
              method: "POST"
              middlewares:
                - name: authz
                  config:
                    actions:
                      - guardian_all_actions
                      - guardian_read
                    attributes:
                      resource_name:
                        value: "provider"                     <-----------------------------------
                        type: constant                        <-----------------------------------
```

- Use `constant` type to assign a constant value to `*` to resource_id to define it as non-resource type. This will be used to enforce authorize for API like admin apis which have no associated resource
```
           - name: create_provider_admin
              path: "/api/v1beta1/provider"
              method: "POST"
              middlewares:
                - name: authz
                  config:
                    actions:
                      - guardian_all_actions
                      - guardian_read
                    attributes:
                      resource_id:
                        value: "*"                               <----------------------------
                        type: constant                           <----------------------------
                      resource_name:
                        value: "provider"
                        type: constant
```
